### ISSUE TITLE
4.1.1 release of collective.js.datatables completly broken?

### ISSUE THREAD

**Issue by thet** [collective/collective.js.datatables#16]
The current release doesn't work for me.
One Problem are RequireJS troubles in my environment, which were reintroduced by merging PR https://github.com/collective/collective.js.datatables/pull/14 , which of course overwrote https://github.com/collective/collective.js.datatables/commit/347ecfd578f04bc647021bfbb450990481bd4b0e (Fixed again in PR https://github.com/collective/collective.js.datatables/pull/15 ).

But now I get this error:
```ReferenceError: _buildInclude is not defined```.
When grepping for ``_buildInclude`` I cannot find a definition of it but many references, starting here: https://github.com/collective/collective.js.datatables/blob/master/collective/js/datatables/resources/media/js/jquery.dataTables.js#L96

Does this release work for anyone?

**Comment by thet** [comment]
Luckily there is a release wich works for me:  3.1.10.5

**Comment by agitator** [comment]
@keul is 4.1.1 working for you with plone5?

**Comment by keul** [comment]
@agitator I quickly tested after the last release and it was working, but to be honest I'm "maintaining" this package just because Jean Michelle left Plone development. I never used this in production in the last year.

BTW: if there's an active maintainer for this I can give him pypi permissions

**Comment by jensens** [comment]
latest master was fixed to work with Plone 4 and 5

**Comment by agitator** [comment]
https://pypi.python.org/pypi/collective.js.datatables/4.1.2 is out
