### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by jensens** [collective/collective.js.datatables#7]
May we have a release of  version 3.1.10.4? Works fine here. I can do it too, just add me (jensens) add pypi ;)

**Comment by keul** [comment]
@jensens shared the project on pypi and plone.org also.
If you can spend 5 minutes more: please release on plone.org also (I know that this is going to be deprecated, but seeing the current state of paragon.plone.org I don't think it will be done in near future :smile: )

**Comment by jensens** [comment]
Release is on pypi, i just have no permission to add a release on plone.org (edit is fine).

![screenshot from 2015-01-29 16 15 52](https://cloud.githubusercontent.com/assets/157140/5959935/337d194e-a7d2-11e4-9021-114dd230ae05.png)

**Comment by keul** [comment]
F...k... I have no permission to gives you "add" permission... plone.org workflow is suboptimal.
Ok, forget it, thanks for trying

**Comment by plone-foundation** [comment]
On 29/01/15 16:34, Luca Fabbri wrote:
> F...k... I have no permission to gives you "add" permission... plone.org
> workflow is suboptimal.
> Ok, forget it, thanks for trying
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/collective/collective.js.datatables/issues/7#issuecomment-72044564>.
> 
@yenzenz I updated you permissions for collective.js.datatables on p.o

**Comment by jensens** [comment]
https://plone.org/products/collective.js.datatables/releases/portal_factory/PSCRelease/2.9/edit results in a (hidden) traceback: The error has been logged as entry number 1422544768.130.927390209853.

**Comment by keul** [comment]
@jensens sdist

In your `~/.pypirc` put:

    [distutils]
    index-servers =
        pypi
        plone.org
    
    ...
    
    [plone.org]
    repository:https://plone.org/products
    username:jensens
    password:*****

Then simply run:

    $ python setup.py register -r plone.org sdist --formats=zip upload -r plone.org

(this is automatically done using using zest.releaser)

However: release on pypi is done, let's close this
